version: 2

references:
  yarn_cache_config: &yarn_cache_config
    key: dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
    paths:
      - node_modules

  yarn_restore_cache: &yarn_restore_cache
    restore_cache:
      <<: *yarn_cache_config
      name: Restore yarn cache

  yarn_save_cache: &yarn_save_cache
    save_cache:
      <<: *yarn_cache_config
      name: Save yarn cache

jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/workspace
    steps:
      - checkout
      - *yarn_restore_cache
      - run: yarn --pure-lockfile
      - *yarn_save_cache
      - run: yarn build
      - run: yarn test
      - run: yarn lint
      - run: yarn format && git diff --exit-code || exit 1
